### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by Cuchulain** [derXge/whatsappsaver#2]
```
$ npm start

> whatsappsaver@1.0.0 start
> node index.js

WARN [2023-01-25 11:05:53.450 +0000] (64013): connect attempt 1 failed: Error: Unexpected server response: 404, retrying...
    class: "Baileys"
    error: {}
WARN [2023-01-25 11:05:57.679 +0000] (64013): connect attempt 2 failed: Error: Unexpected server response: 404, retrying...
    class: "Baileys"
    error: {}
WARN [2023-01-25 11:06:01.850 +0000] (64013): connect attempt 3 failed: Error: Unexpected server response: 404, retrying...
    class: "Baileys"
    error: {}
WARN [2023-01-25 11:06:05.994 +0000] (64013): connect attempt 4 failed: Error: Unexpected server response: 404, retrying...
    class: "Baileys"
    error: {}
WARN [2023-01-25 11:06:10.141 +0000] (64013): connect attempt 5 failed: Error: Unexpected server response: 404, retrying...
    class: "Baileys"
    error: {}
WARN [2023-01-25 11:06:14.417 +0000] (64013): connect attempt 6 failed: Error: Unexpected server response: 404, retrying...
    class: "Baileys"
    error: {}`

**Comment by Cuchulain** [comment]
```
$ python --version
Python 3.11.0

**Comment by xgedev** [comment]
Hey @Cuchulain, Meta / WhatsApp is currently having issues as you can see on their status website: https://metastatus.com/
You might want to wait until all issues are resolved. If it is still not connecting, send a message again here.

**Comment by Cuchulain** [comment]
Hi @xgedev , thanks for info. I'll try again later...

**Comment by finngaida** [comment]
Hey, has this been resolved? I'm seeing the same issue, WA doesn't seem to be down currently.

**Comment by xgedev** [comment]
Hello @finngaida, thank you for bringing this up.

I tried it myself just now and it is not working either.

Unfortunately the library I used to communicate with WhatsApp Web is no longer compatible with it and was deleted. New versions by third-parties are entirely different and I am unable to easily update this repository, sorry.

### Alternative way to backup chats
However, you are able to backup chats natively within WhatsApp now. I have updated [this repository's README](https://github.com/xgedev/whatsappsaver) accordingly.

I hope I could help, have a great day.
